"""Explicit shared cursor and diagnostic contract for parser families."""

from __future__ import annotations

from typing import Any, Protocol


class ParserContext(Protocol):
    """The sole live token cursor and diagnostic owner during extraction."""

    tokens: list[Any]
    i: int
    diagnostics: list[dict]

    def _peek(self) -> Any: ...

    def _advance(self) -> Any: ...

    def _expect(self, kind: Any) -> Any: ...

    def _emit_diagnostic(self, *args: Any, **kwargs: Any) -> Any: ...

    def _recover_top_level(self) -> Any: ...

    def _legacy_parse_declaration(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_parse_scientific_scope(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_parse_statement(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_parse_expression(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_parse_operator_expression(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_recover_top_level(self, *args: Any, **kwargs: Any) -> Any: ...
