"""Staqex production compiler package (Phase 2.1)."""

from .codegen_qasm import OpenQASM3Generator, StaqexCompiler
from .host import (
    DynamicTraceReport,
    Job,
    JobResult,
    MeasurementEnvelope,
    project_dynamic_trace,
    run_path,
    run_source,
    submit_path,
    submit_source,
)
from .pipeline import CompileResult, analyze_source, compile_path, compile_source
from .workflow import (
    ExecutionPolicy,
    JobRequest,
    MeasurementProjection,
    ParamBinding,
    WorkflowPlan,
    WorkflowReport,
    WorkflowValidationError,
)
from .workflow_surface import WorkflowContract
from .discretization import DiscretizationBridge, DiscretizationContract
from .mixed_state import MixedStateContract
from .scientific_input import (
    CoefficientTensor,
    InputProvenance,
    ParameterBinding,
    ParameterSweep,
    ScientificInput,
    ScientificInputValidationError,
)
from .observation import (
    CheckpointIdentity,
    ObservationPlan,
    ObservationReport,
    ObservationRequest,
    ObservationValidationError,
    SnapshotCapability,
    plan_observations,
)
from .observation_execution import (
    FakeObservationValueSource,
    HostExecutionContext,
    LocalObservationAdapter,
    ObservationExecutionPort,
    ObservationExecutionValidationError,
    ObservationValueSource,
)
from .qpu_submit import (
    ProviderJobId,
    ProviderJobState,
    QpuArtifact,
    QpuJobPort,
    QpuSubmitPort,
    QpuSubmitRequest,
)
from .host_monte_carlo import (
    EqualWidthHistogramMonteCarlo,
    FiniteStateInject,
    HostMonteCarloPort,
    HostRngAdapter,
    HostRngPort,
    MonteCarloInjectError,
    MonteCarloSpec,
    finite_inject_to_joint,
    run_host_mc_inject,
)

__all__ = [
    "CompileResult",
    "OpenQASM3Generator",
    "StaqexCompiler",
    "analyze_source",
    "compile_path",
    "compile_source",
    "Job",
    "JobResult",
    "DynamicTraceReport",
    "MeasurementEnvelope",
    "project_dynamic_trace",
    "run_path",
    "run_source",
    "submit_path",
    "submit_source",
    "ExecutionPolicy",
    "JobRequest",
    "MeasurementProjection",
    "ParamBinding",
    "WorkflowPlan",
    "WorkflowReport",
    "WorkflowValidationError",
    "WorkflowContract",
    "DiscretizationContract",
    "DiscretizationBridge",
    "MixedStateContract",
    "InputProvenance",
    "ParameterBinding",
    "ParameterSweep",
    "CoefficientTensor",
    "ScientificInput",
    "ScientificInputValidationError",
    "CheckpointIdentity",
    "ObservationPlan",
    "ObservationReport",
    "ObservationRequest",
    "ObservationValidationError",
    "SnapshotCapability",
    "plan_observations",
    "FakeObservationValueSource",
    "HostExecutionContext",
    "LocalObservationAdapter",
    "ObservationExecutionPort",
    "ObservationExecutionValidationError",
    "ObservationValueSource",
    "ProviderJobId",
    "ProviderJobState",
    "QpuArtifact",
    "QpuJobPort",
    "QpuSubmitPort",
    "QpuSubmitRequest",
    "EqualWidthHistogramMonteCarlo",
    "FiniteStateInject",
    "HostMonteCarloPort",
    "HostRngAdapter",
    "HostRngPort",
    "MonteCarloInjectError",
    "MonteCarloSpec",
    "finite_inject_to_joint",
    "run_host_mc_inject",
]
