"""Explicit context contract for extracted typechecking families."""

from __future__ import annotations

from typing import Any, Protocol


class TypeCheckContext(Protocol):
    """The single live environment and diagnostic owner for typechecking."""

    env: dict[str, Any]
    diagnostics: list[dict]

    def _check_declaration(self, *args: Any, **kwargs: Any) -> Any: ...

    def _check_operator(self, *args: Any, **kwargs: Any) -> Any: ...

    def _check_dimensions(self, *args: Any, **kwargs: Any) -> Any: ...

    def _infer_expression(self, *args: Any, **kwargs: Any) -> Any: ...

    def _check_evolution(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_check_declaration(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_check_operator(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_check_dimensions(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_infer_expression(self, *args: Any, **kwargs: Any) -> Any: ...

    def _legacy_check_evolution(self, *args: Any, **kwargs: Any) -> Any: ...
